"""
threattracer.cli.report
~~~~~~~~~~~~~~~~~~~~~~~~
Self-contained Markdown / HTML report writer.

No heavy dependencies: Markdown is plain text; HTML is a single inlined-CSS file
that renders in any browser and prints cleanly to PDF (Ctrl-P → Save as PDF).
"""

from __future__ import annotations

import html
import logging
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Optional

from threattracer.utils.models import (
    CVERecord,
    LLMSummary,
    ScanSummary,
    Severity,
    TriageItem,
)

log = logging.getLogger(__name__)

_SEV_BADGE = {
    Severity.CRITICAL: "🔴 CRITICAL",
    Severity.HIGH: "🟠 HIGH",
    Severity.MEDIUM: "🟡 MEDIUM",
    Severity.LOW: "🟢 LOW",
    Severity.NONE: "⚪ NONE",
    Severity.UNKNOWN: "❓ UNKNOWN",
}


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


# ── Markdown ────────────────────────────────────────────────────────────────

def build_markdown(
    summary: ScanSummary,
    records: List[CVERecord],
    llm: Optional[LLMSummary] = None,
) -> str:
    out: List[str] = []
    out.append(f"# ThreatTracer Report — {summary.target or 'scan'}")
    out.append("")
    out.append(f"*Generated {_now()} · scan type: `{summary.scan_type}`*")
    out.append("")

    if llm and llm.text:
        engine = "local LLM" if llm.engine in ("ollama", "openai") else "heuristic"
        out.append("## Executive Summary")
        out.append("")
        out.append(f"> _Generated by {engine}"
                   + (f" (`{llm.model}`)" if llm.model and not llm.degraded else "")
                   + (f" — {llm.note}" if llm.degraded and llm.note else "")
                   + "_")
        out.append("")
        out.append(llm.text)
        out.append("")

    out.append("## At a Glance")
    out.append("")
    out.append("| Metric | Count |")
    out.append("|---|---|")
    out.append(f"| Total CVEs | {summary.total_cves} |")
    out.append(f"| Critical | {summary.critical} |")
    out.append(f"| High | {summary.high} |")
    out.append(f"| In CISA KEV | {summary.in_kev} |")
    out.append(f"| Ransomware-linked | {summary.ransomware_linked} |")
    out.append(f"| Weaponised (MSF/KEV) | {summary.weaponised} |")
    out.append(f"| With Exploit-DB entry | {summary.with_edb} |")
    out.append(f"| With public PoC | {summary.with_poc} |")
    out.append(f"| With Nuclei template | {summary.with_nuclei} |")
    out.append("")

    if summary.top_findings:
        out.append("## Prioritised Findings")
        out.append("")
        out.append("| # | CVE | Priority | Severity | CVSS | EPSS | Signals |")
        out.append("|---|---|---|---|---|---|---|")
        for i, item in enumerate(summary.top_findings, 1):
            cvss = f"{item.cvss_score:.1f}" if item.cvss_score is not None else "—"
            epss = f"{item.epss_score * 100:.0f}%" if item.epss_score is not None else "—"
            sig = ", ".join(item.signals) or "—"
            comp = f" ({item.component})" if item.component else ""
            out.append(
                f"| {i} | [{item.cve_id}]({item.nvd_link}){comp} | "
                f"{item.priority_score:.0f} | {item.severity.value} | {cvss} | {epss} | {sig} |"
            )
        out.append("")

    if records:
        out.append("## Full CVE Detail")
        out.append("")
        for r in records:
            out.append(f"### {r.cve_id} — {_SEV_BADGE.get(r.severity, r.severity.value)}")
            out.append("")
            if r.description and r.description != "N/A":
                out.append(r.description.strip())
                out.append("")
            meta = []
            if r.cvss_score is not None:
                meta.append(f"**CVSS:** {r.cvss_score}")
            if r.epss_score is not None:
                meta.append(f"**EPSS:** {r.epss_score * 100:.1f}%")
            if r.in_kev:
                meta.append(f"**CISA KEV:** added {r.kev_date_added} "
                            f"(ransomware: {r.kev_ransomware_use or 'unknown'})")
            if meta:
                out.append(" · ".join(meta))
                out.append("")
            if r.exploits:
                out.append(f"- **Exploit-DB ({len(r.exploits)}):** " +
                           ", ".join(f"[EDB-{e.id}]({e.link})" for e in r.exploits[:6]))
            if r.pocs:
                out.append(f"- **PoCs ({len(r.pocs)}):** " +
                           ", ".join(f"[{p.url.split('/')[-1] or p.url}]({p.url})"
                                     for p in r.pocs[:6]))
            if r.nuclei_templates:
                out.append(f"- **Nuclei:** `nuclei -t cves/ -id {r.cve_id.lower()}`")
            if r.msf_modules:
                out.append(f"- **Metasploit:** `use {r.msf_modules[0].fullname}`")
            out.append("")

    out.append("---")
    out.append("")
    out.append("_ThreatTracer aggregates public vulnerability intelligence for "
               "authorised testing and defensive triage. Priority scores are "
               "decision support, not a guarantee of exploitability._")
    out.append("")
    return "\n".join(out)


# ── HTML ────────────────────────────────────────────────────────────────────

_HTML_CSS = """
:root { --bg:#0d1117; --card:#161b22; --fg:#e6edf3; --muted:#8b949e;
        --crit:#f85149; --high:#ff7b52; --med:#e3b341; --low:#3fb950; --acc:#58a6ff; }
* { box-sizing: border-box; }
body { margin:0; background:var(--bg); color:var(--fg);
       font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Helvetica,Arial,sans-serif; }
.wrap { max-width: 980px; margin: 0 auto; padding: 40px 24px 80px; }
h1 { font-size: 26px; margin: 0 0 4px; }
h2 { font-size: 19px; margin: 34px 0 12px; border-bottom:1px solid #30363d; padding-bottom:6px; }
h3 { font-size: 16px; margin: 22px 0 6px; }
.sub { color: var(--muted); font-size: 13px; margin-bottom: 24px; }
.exec { background: var(--card); border:1px solid #30363d; border-left:4px solid var(--acc);
        border-radius:8px; padding:18px 20px; white-space:pre-wrap; }
.exec .by { color: var(--muted); font-size:12px; margin-bottom:10px; }
.cards { display:flex; flex-wrap:wrap; gap:12px; }
.card { background:var(--card); border:1px solid #30363d; border-radius:8px;
        padding:14px 18px; min-width:120px; flex:1; }
.card .n { font-size:26px; font-weight:700; }
.card .l { color:var(--muted); font-size:12px; text-transform:uppercase; letter-spacing:.5px; }
table { width:100%; border-collapse:collapse; margin:8px 0 20px; font-size:13.5px; }
th,td { text-align:left; padding:8px 10px; border-bottom:1px solid #21262d; vertical-align:top; }
th { color:var(--muted); font-weight:600; }
a { color:var(--acc); text-decoration:none; } a:hover { text-decoration:underline; }
.sev-CRITICAL { color:var(--crit); font-weight:700; } .sev-HIGH { color:var(--high); font-weight:600; }
.sev-MEDIUM { color:var(--med); } .sev-LOW { color:var(--low); }
.badge { display:inline-block; padding:1px 8px; border-radius:10px; font-size:11px;
         background:#21262d; color:var(--muted); margin:1px 2px; }
.kev { background:#3d1c1c; color:#ff9c8f; }
code { background:#21262d; padding:2px 6px; border-radius:4px; font-size:12.5px; }
.foot { color:var(--muted); font-size:12px; margin-top:40px; border-top:1px solid #30363d; padding-top:16px; }
@media print { body { background:#fff; color:#111; } .exec,.card { background:#f6f8fa; }
               a { color:#0969da; } }
"""


def _sev_cell(sev: Severity) -> str:
    return f'<span class="sev-{sev.value}">{sev.value}</span>'


def build_html(
    summary: ScanSummary,
    records: List[CVERecord],
    llm: Optional[LLMSummary] = None,
) -> str:
    e = html.escape

    def card(n, label: str) -> str:
        return f'<div class="card"><div class="n">{n}</div><div class="l">{label}</div></div>'

    exec_block = ""
    if llm and llm.text:
        engine = "local LLM" if llm.engine in ("ollama", "openai") else "heuristic engine"
        by = f"Generated by {engine}"
        if llm.model and not llm.degraded:
            by += f" ({e(llm.model)})"
        if llm.degraded and llm.note:
            by += f" — fell back: {e(llm.note)}"
        exec_block = (
            '<h2>Executive Summary</h2>'
            f'<div class="exec"><div class="by">{by}</div>{e(llm.text)}</div>'
        )

    rows = []
    for i, item in enumerate(summary.top_findings, 1):
        cvss = f"{item.cvss_score:.1f}" if item.cvss_score is not None else "—"
        epss = f"{item.epss_score * 100:.0f}%" if item.epss_score is not None else "—"
        badges = "".join(
            f'<span class="badge {"kev" if s in ("CISA KEV", "ransomware") else ""}">{e(s)}</span>'
            for s in item.signals
        ) or "—"
        comp = f' <span class="badge">{e(item.component)}</span>' if item.component else ""
        rows.append(
            f"<tr><td>{i}</td>"
            f'<td><a href="{e(item.nvd_link)}">{e(item.cve_id)}</a>{comp}</td>'
            f"<td><b>{item.priority_score:.0f}</b></td>"
            f"<td>{_sev_cell(item.severity)}</td>"
            f"<td>{cvss}</td><td>{epss}</td><td>{badges}</td></tr>"
        )
    findings_table = (
        "<h2>Prioritised Findings</h2><table><tr><th>#</th><th>CVE</th>"
        "<th>Priority</th><th>Severity</th><th>CVSS</th><th>EPSS</th><th>Signals</th></tr>"
        + "".join(rows) + "</table>"
        if rows else ""
    )

    detail = []
    for r in records:
        chips = []
        if r.exploits:
            chips.append(f'<span class="badge">Exploit-DB ×{len(r.exploits)}</span>')
        if r.pocs:
            chips.append(f'<span class="badge">PoC ×{len(r.pocs)}</span>')
        if r.nuclei_templates:
            chips.append('<span class="badge">Nuclei</span>')
        if r.msf_modules:
            chips.append('<span class="badge">Metasploit</span>')
        if r.in_kev:
            chips.append('<span class="badge kev">CISA KEV</span>')
        desc = e((r.description or "").strip()[:600])
        detail.append(
            f'<h3><a href="{e(r.nvd_link)}">{e(r.cve_id)}</a> · {_sev_cell(r.severity)}</h3>'
            f"<div>{desc}</div><div style='margin-top:6px'>{''.join(chips)}</div>"
        )
    detail_block = "<h2>Full CVE Detail</h2>" + "".join(detail) if detail else ""

    cards = "".join([
        card(summary.total_cves, "Total CVEs"),
        card(summary.critical, "Critical"),
        card(summary.in_kev, "In KEV"),
        card(summary.weaponised, "Weaponised"),
        card(summary.with_poc, "With PoC"),
    ])

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>ThreatTracer Report — {e(summary.target or 'scan')}</title>
<style>{_HTML_CSS}</style></head>
<body><div class="wrap">
<h1>ThreatTracer Report</h1>
<div class="sub">{e(summary.target or 'scan')} · {e(_now())} · scan type: <code>{e(summary.scan_type)}</code></div>
{exec_block}
<h2>At a Glance</h2><div class="cards">{cards}</div>
{findings_table}
{detail_block}
<div class="foot">ThreatTracer aggregates public vulnerability intelligence for authorised
testing and defensive triage. Priority scores are decision support, not a guarantee of
exploitability.</div>
</div></body></html>"""


def write_report(
    path: Path,
    summary: ScanSummary,
    records: List[CVERecord],
    llm: Optional[LLMSummary] = None,
) -> Path:
    """Write a report to ``path``; format inferred from the extension (.md/.html)."""
    suffix = path.suffix.lower()
    if suffix in (".html", ".htm"):
        content = build_html(summary, records, llm)
    else:
        content = build_markdown(summary, records, llm)
        if suffix != ".md":
            path = path.with_suffix(".md")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return path
